spring.application.name=facturacion-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d8o1t90g4nts73c6mup0-a.oregon-postgres.render.com:5432/facturacion_1654

# Usuario de PostgreSQL
spring.datasource.username=gdl

# Contraseña de PostgreSQL
spring.datasource.password=QgVdG8oVJVGJxODmheBtIpeargUJgC0K

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=Nf72KpA9xQmL48vZsP1rC6tBqW9uH3yTgR5eV8bM2nJ4kL7wXcD6sQ1pF8zB3a
jwt.expiration=3600000

# SRE API
sre.api.url=https://sre.cl/api/company_info
sre.api.token=58e112bf-2807-44c3-aad6-0b9e4543a559
